# Set the working directory in the container



# Copy the JAR file into the container
COPY tv-0.0.1-SNAPSHOT.jar app.jar

# Expose the port your application listens on (change if needed)
EXPOSE 8080

# Run the application
CMD ["java", "-jar", "app.jar"]
